"""Initial schema

Revision ID: 89f65426f474
Revises: 
Create Date: 2026-07-18 18:15:56.131494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89f65426f474'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False, comment='Human-readable ID, e.g., rule_escalation_001'),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False, comment='escalation | compliance | qualification | payment'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='threshold | pattern | schedule | checklist'),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Declarative condition, e.g., {"field": "objection_count", "operator": "gte", "value": 3}'),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Action to take, e.g., {"type": "escalate", "reason": "Multiple unresolved objections"}'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Higher priority = evaluated first'),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False, comment='all | india | philippines | indonesia'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_rules_category'), 'business_rules', ['category'], unique=False)
    op.create_index(op.f('ix_business_rules_rule_id'), 'business_rules', ['rule_id'], unique=True)
    op.create_table('calls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_call_id', sa.String(length=200), nullable=True, comment='Vapi call ID'),
    sa.Column('borrower_name', sa.String(length=200), nullable=True),
    sa.Column('loan_id', sa.String(length=100), nullable=True),
    sa.Column('loan_type', sa.String(length=50), nullable=True, comment='personal | home | auto | business'),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='active | completed | escalated | failed'),
    sa.Column('outcome', sa.String(length=50), nullable=True, comment='commitment | callback | escalation | refused | no_answer'),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commitment_date', sa.Date(), nullable=True, comment='Date borrower committed to pay'),
    sa.Column('callback_scheduled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full conversation transcript as JSON'),
    sa.Column('summary', sa.Text(), nullable=True, comment='LLM-generated call summary'),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True, comment='Overall call sentiment (-1.0 to 1.0)'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='duration_seconds, agent_id, recording_url, etc.'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='india | philippines | indonesia'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_external_call_id'), 'calls', ['external_call_id'], unique=True)
    op.create_index(op.f('ix_calls_loan_id'), 'calls', ['loan_id'], unique=False)
    op.create_table('kb_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(length=100), nullable=False, comment='Human-readable ID, e.g., kb_loan_policy_001'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_clean', sa.Text(), nullable=True, comment='PII-redacted version of content'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='product | policy | faq | objection | compliance | payment | escalation'),
    sa.Column('subcategory', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False, comment='website | pdf | manual | csv'),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('contains_pii', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='tags, language, product_type, applicable_market, etc.'),
    sa.Column('chunk_id', sa.String(length=100), nullable=True, comment='Chunk identifier within parent doc'),
    sa.Column('parent_doc_id', sa.String(length=100), nullable=True, comment='Links chunk to parent document'),
    sa.Column('embedding_id', sa.String(length=200), nullable=True, comment='Pinecone vector ID'),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_records_category'), 'kb_records', ['category'], unique=False)
    op.create_index(op.f('ix_kb_records_parent_doc_id'), 'kb_records', ['parent_doc_id'], unique=False)
    op.create_index(op.f('ix_kb_records_record_id'), 'kb_records', ['record_id'], unique=True)
    op.create_table('call_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False, comment='state_change | tool_call | rag_query | escalation | error | compliance_check'),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    op.create_table('nudges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(length=50), nullable=False, comment='compliance_gap | sentiment | cross_sell | missed_opportunity | payment_difficulty | risk'),
    sa.Column('signal_text', sa.Text(), nullable=False, comment='What was detected in the conversation'),
    sa.Column('nudge_text', sa.Text(), nullable=False, comment='Actionable recommendation for the agent'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence score 0.0 - 1.0'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='critical | high | medium | low'),
    sa.Column('displayed', sa.Boolean(), nullable=False, comment='Was this nudge shown to the agent'),
    sa.Column('suppressed', sa.Boolean(), nullable=False, comment='Was this nudge filtered out by controls'),
    sa.Column('suppression_reason', sa.String(length=100), nullable=True, comment='duplicate | cooldown | low_confidence | max_per_call | expired'),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"asr": 180, "signal": 95, "llm": 320, "delivery": 15, "total": 610}'),
    sa.Column('transcript_position', sa.Integer(), nullable=True, comment='Word offset in transcript when signal was detected'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nudges_call_id'), 'nudges', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nudges_call_id'), table_name='nudges')
    op.drop_table('nudges')
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_kb_records_record_id'), table_name='kb_records')
    op.drop_index(op.f('ix_kb_records_parent_doc_id'), table_name='kb_records')
    op.drop_index(op.f('ix_kb_records_category'), table_name='kb_records')
    op.drop_table('kb_records')
    op.drop_index(op.f('ix_calls_loan_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_external_call_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_business_rules_rule_id'), table_name='business_rules')
    op.drop_index(op.f('ix_business_rules_category'), table_name='business_rules')
    op.drop_table('business_rules')
    # ### end Alembic commands ###